### PR TITLE
Fix singular, abbreviated day unit.

### PR DESCRIPTION
**Pull request by calebd**
This brings the key in line with what is present in the localized strings files.

### CODE REVIEW

**Comment by sebastianludwig** [comment]
I object. By using the same key for the abbreviated and regular version it's not possible to use different words for them. This becomes even more important for localizations with longer words for day/days. The correct fix would be to use `ds` (or something alike) for the plural abbreviated key and fix the localization files instead.

**Comment by calebd** [comment]
I mean, the localized strings file literally does not have a key that matches what the source code had. Fix it however you like, but it was wrong and not it's not.

**Comment by calebd** [comment]
@sebastianludwig That's great but the source code in this branch still references a key that does not exist. So it will _always_ display `d`.

**Comment by calebd** [comment]
Also fixed a bug introduced in a previous pull request in which week data was dropped from all relative date formats.

**Comment by sebastianludwig** [comment]
Hi @calebd, I just submitted #185. It adds localization keys for `d` and `ds`. With this it'd be possible to provide different translations for the abbreviated and non-abbreviated versions. What do you think?

If you agree, could you separate your fix of 241feb6 into it's own PR to allow independent merging?

**Comment by calebd** [comment]
@sebastianludwig Opened #186.

**Pull request closed without merging**
