### PR TITLE
Added unit tests and Travis CI integration for TTTTimeIntervalFormatter

### PR DESCRIPTION
**Pull request by bizz84**
This only includes some unit-test coverage for non-idiomatic expressions

### CODE REVIEW

**Comment by sebastianludwig** [comment]
Can't give enough :+1: for this PR. This lib, with apparently many ppl. (>3k :star:) depending on it, desperately needs _some_ unit tests. This is a good start!

Do you have an idea why cmd+U doesn't run the unit tests in Xcode?

**Comment by bizz84** [comment]
Hi Matt,

What version of XCode are you running on? I tested it on 6.3.2 and 7.0 beta
3 and the tests run fine.

Glad you like it :)

Andrea


On 23 July 2015 at 18:21, sebastianludwig <notifications@github.com> wrote:

> Can't give enough [image: :+1:] for this PR. This lib, with apparently
> many ppl. (>3k [image: :star:]) depending on it, desperately needs *some*
> unit tests. This is a good start!
>
> Do you have an idea why cmd+U doesn't run the unit tests in Xcode?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattt/FormatterKit/pull/170#issuecomment-124156205>.
>



-- 
Andrea Bizzotto
Software Developer and Consultant
mobile: +44 753 110 1563
e-mail: bizz84@gmail.com
Personal website: www.bizzotto.biz
Company website: www.musevisions.com
Got an Oyster Card? Try this: taps.io/MyOyster
<https://itunes.apple.com/app/id784860215>

**Comment by sebastianludwig** [comment]
Hi Andrea, 

I'm not @mattt so unfortunately my liking it doesn't count too much and I can't merge your PR ;-)

To be able to run the unit tests while having the app target selected I had to add them to the scheme. I'll send you a PR soon.

**Comment by sebastianludwig** [comment]
Ah well, seems I can't GitHub to offer me your branch as PR base/destination. Maybe you can include the fix yourself?

To be able to run the tests with `cmd+u` while the "Formatter Kit Examples" scheme is selected I had to edit that scheme, select "Test", press the "+" on the bottom and add "FormatterKitTests". Then that scheme needs to be shared, too.

**Comment by bizz84** [comment]
I merged back this branch to master on my fork. As part of this I updated the .travis.yml file to ensure that the build and test passes.
I did not encounter any problems upon checking out the new master branch and running the tests as the original scheme appeared to be shared already. Please check my new PR regarding this.

**Pull request closed without merging**
