### PR TITLE
Fixes bug introduced in 05aeefc.

### PR DESCRIPTION
**Pull request by calebd**
Fixed a bug introduced in a previous pull request in which week data was dropped from all relative date formats.

### CODE REVIEW

**Comment by sebastianludwig** [comment]
Nice! Now all we need is a merge :-)

**Comment by sebastianludwig** [comment]
Taking a second look, this does not look right. The two `switch (b)`s look odd. To get a little bit more scientific, I wrote the following test

```objc
- (void)testCompare {
    NSCalendarUnit units[] = {NSCalendarUnitSecond, NSCalendarUnitMinute, NSCalendarUnitHour, NSCalendarUnitDay, NSCalendarUnitWeekOfYear, NSCalendarUnitMonth, NSCalendarUnitYear};
    
    for (int o = 0; o < 7; ++o) {
        NSCalendarUnit baseUnit = units[o];
        NSComparisonResult expected = NSOrderedDescending;
        for (int i = 0; i < 7; ++i) {
            if (units[i] == baseUnit) {
                XCTAssertEqual(NSCalendarUnitCompareSignificance(baseUnit, units[i]), NSOrderedSame);
                expected = NSOrderedAscending;
            } else if (NSCalendarUnitCompareSignificance(baseUnit, units[i]) != expected) {
                XCTFail(@"mismatch");
            }
        }
    }
}
```

The tests do not pass with your changes, but did before.

Could you provide example input where week data was dropped before your change and is included with your fix?

**Comment by calebd** [comment]
Code:

```swift
let formatter = TTTTimeIntervalFormatter()
let string = formatter.stringForTimeInterval(60 * 60 * 24 * 10 * -1)
println(string)
```

With my change: `1 week ago`

Without my change: `3 days ago`

To test: `pod 'FormatterKit/TimeIntervalFormatter', git: 'https://github.com/hodinkee/FormatterKit', commit: '2b977f3fbdb34018161e2bb6b4f99bc5af9d2df5'`

**Comment by calebd** [comment]
As stated in my pull request message: Week data is dropped from all relative dates. The regression was introduced in the commit that I addressed.

**Comment by sebastianludwig** [comment]
Hey, thanks for the example! Still, I'm pretty sure line 78 should be a `switch (a)`. Otherwise anything compared to `TTTCalendarUnitWeek` would be `NSOrderedAscending` (`NSCalendarUnitCompareSignificance(<anyUnit>, TTTCalendarUnitWeek)` leads to the `return` in line 83).

**Comment by calebd** [comment]
Whatever it takes to make the library work as advertised. TBH that method should be rewritten entirely. The fact that neither of us can make sense of how it should work is indicative of poor logic in the first place.

**Comment by sebastianludwig** [comment]
Well, it compares two `NSCalendarUnits` based on their raw enum values which are defined based on `CFCalendarUnit`. However `kCFCalendarUnitWeekOfYear` is listed after `kCFCalendarUnitSecond` (and has a higher value assigned) thus the special handling.

And about getting this lib to work I'm more concerned about @mattt's abstinence for months. Anyway, I realized FormatterKit doesn't completely fit my needs and started working on a different lib (to be release next weekend). Will give you shout, maybe it's of any help for you, too.

**Comment by mjstallard** [comment]
@sebastianludwig did you ever get around to releasing that lib? FormatterKit seemed to be suitable for my date formatting needs, but it looks like it's abandonware at this point. Would love to find some alternatives.

**Comment by sebastianludwig** [comment]
Oh, sorry, I forgot about my promise to mention it here: [LDOConditionalDateFormatter](https://github.com/lurado/LDOConditionalDateFormatter)

Please don't hesitate to give feedback

**Comment by yas375** [comment]
The issue was fixed in #162.

I agree this method should be refactored to be more readable and to be independent from enum row values.

**Pull request closed without merging**
